name: activityrank

configs:
  privileges:
    file: ./config/privileges.json
  config:
    file: ./config/config.json

secrets:
  keys:
    file: ./config/keys.json

services:
  db:
    container_name: Database
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  
  manager:
    container_name: Manager
    restart: always
    init: true
    build:
      context: .
      dockerfile: apps/manager/Dockerfile
    image: 'activityrank/manager:dev'
    depends_on:
      - db
    links:
      - db
    ports:
      - '3005:3000'
    secrets:
      - keys
    configs:
      - config

  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    container_name: Bot
    configs:
      - privileges
      - config
    secrets:
      - keys

  api:
    container_name: Public API
    restart: always
    init: true
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: 'activityrank/api:dev'
    depends_on:
      - db
      - manager
    links:
      - db
      - manager
    ports:
      - '8080:3000'
    secrets:
      - keys
    configs:
      - config
